language: python

python:
- 3.7

dist: xenial

sudo: true

addons:
  apt_packages:
  - libcups2-dev

services:
- mysql

install:
- pip install --upgrade pip
- pip install flake8 coveralls mysqlclient tox-travis
- pip install -e .
- pip install -q -r requirements.txt

before_script:
- flake8 edc_model_admin
- mysql -e 'create database edc character set utf8;'

script:
- coverage run --source=edc_model_admin -m tox-travis
after_success:
- coveralls
