language: python

python:
- 3.7

dist: xenial

sudo: true

addons:
  apt_packages:
  - libcups2-dev

install:
- pip install --upgrade pip
- pip install flake8 coveralls mysqlclient tox-travis

before_script:
- flake8 edc_model_admin

script:
- coverage run -m tox

after_success:
- coveralls
